# Generated by Django 2.1.2 on 2018-10-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('maquina_pt', models.CharField(max_length=255)),
                ('maquina_en', models.CharField(max_length=255)),
                ('maquina_ch', models.CharField(max_length=255)),
                ('tipo_pt', models.CharField(max_length=255)),
                ('tipo_en', models.CharField(max_length=255)),
                ('tipo_ch', models.CharField(max_length=255)),
                ('modelo_pt', models.CharField(max_length=255)),
                ('modelo_en', models.CharField(max_length=255)),
                ('modelo_ch', models.CharField(max_length=255)),
                ('area_trabalho_pt', models.CharField(max_length=255)),
                ('area_trabalho_en', models.CharField(max_length=255)),
                ('area_trabalho_ch', models.CharField(max_length=255)),
                ('eixo_z_pt', models.CharField(max_length=255)),
                ('eixo_z_en', models.CharField(max_length=255)),
                ('eixo_z_ch', models.CharField(max_length=255)),
                ('cor_pt', models.CharField(max_length=255)),
                ('cor_en', models.CharField(max_length=255)),
                ('cor_ch', models.CharField(max_length=255)),
                ('faz_pt', models.TextField()),
                ('faz_en', models.TextField()),
                ('faz_ch', models.TextField()),
                ('voltagem_pt', models.CharField(max_length=10)),
                ('voltagem_en', models.CharField(max_length=10)),
                ('voltagem_ch', models.CharField(max_length=10)),
                ('ncm', models.CharField(max_length=20)),
                ('nome_classificacao', models.TextField()),
                ('caixa_lateral_base', models.CharField(max_length=255)),
                ('opcionais', models.TextField()),
                ('imagem', models.ImageField(upload_to='products/')),
            ],
            options={
                'verbose_name': 'máquina',
                'verbose_name_plural': 'máquinas',
            },
        ),
    ]
