# Generated by Django 2.1.2 on 2018-10-16 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20181015_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('description', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('dolar_dia', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('produtcs', models.ManyToManyField(blank=True, to='core.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotaItens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('valor_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Product')),
                ('nota', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Nota')),
            ],
        ),
    ]
