# Generated by Django 2.1.2 on 2018-10-16 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_nota_notaitens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='produtcs',
        ),
    ]
