# Generated by Django 2.1.2 on 2018-10-16 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_nota_produtcs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ('date', 'description'), 'verbose_name': 'nota', 'verbose_name_plural': 'notas'},
        ),
    ]
