# Generated by Django 2.1.2 on 2018-10-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181015_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaitens',
            name='item',
        ),
        migrations.RemoveField(
            model_name='notaitens',
            name='nota',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
        migrations.DeleteModel(
            name='NotaItens',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
