# Generated by Django 2.1.4 on 2018-12-12 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notaitens',
            options={'verbose_name': 'Item', 'verbose_name_plural': 'Itens'},
        ),
    ]
