# Generated by Django 2.1.5 on 2019-01-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_auto_20181212_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='ncm',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='voltagem_ch',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='voltagem_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='voltagem_pt',
            field=models.CharField(max_length=255),
        ),
    ]
