# Generated by Django 2.2.6 on 2019-11-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0003_auto_20190107_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imagem',
            field=models.URLField(blank=True, default='https://via.placeholder.com/150', null=True),
        ),
    ]
