# Generated by Django 2.2.7 on 2019-11-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0004_auto_20191101_1417'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('maquina_pt', 'tipo_pt', 'modelo_pt'), 'verbose_name': 'máquina', 'verbose_name_plural': 'máquinas'},
        ),
        migrations.AddField(
            model_name='product',
            name='altura',
            field=models.PositiveIntegerField(default=0, verbose_name='Altura em cm'),
        ),
        migrations.AddField(
            model_name='product',
            name='codigo_sku',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Código do produto no Bling'),
        ),
        migrations.AddField(
            model_name='product',
            name='largura',
            field=models.PositiveIntegerField(default=0, verbose_name='Largura em cm'),
        ),
        migrations.AddField(
            model_name='product',
            name='peso_bruto',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Peso Bruto em Kg'),
        ),
        migrations.AddField(
            model_name='product',
            name='peso_liquido',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Peso Líquido em Kg'),
        ),
        migrations.AddField(
            model_name='product',
            name='preco_custo',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=16, verbose_name='Preço de custo em ¥'),
        ),
        migrations.AddField(
            model_name='product',
            name='preco_federal',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=16, verbose_name='Preço federal'),
        ),
        migrations.AddField(
            model_name='product',
            name='profundidade',
            field=models.PositiveIntegerField(default=0, verbose_name='Profundidade em cm'),
        ),
    ]
