# Generated by Django 2.2.7 on 2019-11-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0005_auto_20191106_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='altura',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Altura em cm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='largura',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Largura em cm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='peso_bruto',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Peso Bruto em Kg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='peso_liquido',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='Peso Líquido em Kg'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preco_custo',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=16, null=True, verbose_name='Preço de custo em ¥'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preco_federal',
            field=models.DecimalField(blank=True, decimal_places=10, default=0.0, max_digits=16, null=True, verbose_name='Preço federal'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profundidade',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Profundidade em cm'),
        ),
    ]
