# Generated by Django 2.2.7 on 2019-11-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0006_auto_20191106_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='altura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Altura em cm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='largura',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Largura em cm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='profundidade',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Profundidade em cm'),
        ),
    ]
